/**
 * @fileoverview gRPC-Web generated client stub for history
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: proto/history/history.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_history_history_pb from '../../proto/history/history_pb'; // proto import: "proto/history/history.proto"


export class HistoryServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetHistory = new grpcWeb.MethodDescriptor(
    '/history.HistoryService/GetHistory',
    grpcWeb.MethodType.UNARY,
    proto_history_history_pb.GetHistoryRequest,
    proto_history_history_pb.GetHistoryResponse,
    (request: proto_history_history_pb.GetHistoryRequest) => {
      return request.serializeBinary();
    },
    proto_history_history_pb.GetHistoryResponse.deserializeBinary
  );

  getHistory(
    request: proto_history_history_pb.GetHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_history_history_pb.GetHistoryResponse>;

  getHistory(
    request: proto_history_history_pb.GetHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_history_history_pb.GetHistoryResponse) => void): grpcWeb.ClientReadableStream<proto_history_history_pb.GetHistoryResponse>;

  getHistory(
    request: proto_history_history_pb.GetHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_history_history_pb.GetHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/history.HistoryService/GetHistory',
        request,
        metadata || {},
        this.methodDescriptorGetHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/history.HistoryService/GetHistory',
    request,
    metadata || {},
    this.methodDescriptorGetHistory);
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/history.HistoryService/GetUser',
    grpcWeb.MethodType.UNARY,
    proto_history_history_pb.GetUserRequest,
    proto_history_history_pb.GetUserResponse,
    (request: proto_history_history_pb.GetUserRequest) => {
      return request.serializeBinary();
    },
    proto_history_history_pb.GetUserResponse.deserializeBinary
  );

  getUser(
    request: proto_history_history_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_history_history_pb.GetUserResponse>;

  getUser(
    request: proto_history_history_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_history_history_pb.GetUserResponse) => void): grpcWeb.ClientReadableStream<proto_history_history_pb.GetUserResponse>;

  getUser(
    request: proto_history_history_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_history_history_pb.GetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/history.HistoryService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/history.HistoryService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

}

