// source: proto/gestion/gestion.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.gestion.Gestion', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gestion.Gestion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gestion.Gestion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gestion.Gestion.displayName = 'proto.gestion.Gestion';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gestion.Gestion.prototype.toObject = function(opt_includeInstance) {
  return proto.gestion.Gestion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gestion.Gestion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gestion.Gestion.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createAt: jspb.Message.getFieldWithDefault(msg, 2, 0),
    updateAt: jspb.Message.getFieldWithDefault(msg, 3, 0),
    productionBatchId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    dluo: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    dlv: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    dlc: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    nbrJoursDluo: jspb.Message.getFieldWithDefault(msg, 8, ""),
    nbrJoursDlv: jspb.Message.getFieldWithDefault(msg, 9, ""),
    gestionDeLot: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    blocageEntree: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    blocageSortie: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    alerteStock: jspb.Message.getFieldWithDefault(msg, 13, ""),
    typeAlerte: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gestion.Gestion}
 */
proto.gestion.Gestion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gestion.Gestion;
  return proto.gestion.Gestion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gestion.Gestion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gestion.Gestion}
 */
proto.gestion.Gestion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreateAt(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdateAt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductionBatchId(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDluo(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDlv(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDlc(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setNbrJoursDluo(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setNbrJoursDlv(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGestionDeLot(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBlocageEntree(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBlocageSortie(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlerteStock(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setTypeAlerte(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gestion.Gestion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gestion.Gestion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gestion.Gestion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gestion.Gestion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreateAt();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getUpdateAt();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getProductionBatchId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDluo();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getDlv();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDlc();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getNbrJoursDluo();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getNbrJoursDlv();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getGestionDeLot();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getBlocageEntree();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getBlocageSortie();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getAlerteStock();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getTypeAlerte();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.gestion.Gestion.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 create_at = 2;
 * @return {number}
 */
proto.gestion.Gestion.prototype.getCreateAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setCreateAt = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 update_at = 3;
 * @return {number}
 */
proto.gestion.Gestion.prototype.getUpdateAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setUpdateAt = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string production_batch_id = 4;
 * @return {string}
 */
proto.gestion.Gestion.prototype.getProductionBatchId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setProductionBatchId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool dluo = 5;
 * @return {boolean}
 */
proto.gestion.Gestion.prototype.getDluo = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setDluo = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool dlv = 6;
 * @return {boolean}
 */
proto.gestion.Gestion.prototype.getDlv = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setDlv = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool dlc = 7;
 * @return {boolean}
 */
proto.gestion.Gestion.prototype.getDlc = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setDlc = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional string nbr_jours_dluo = 8;
 * @return {string}
 */
proto.gestion.Gestion.prototype.getNbrJoursDluo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setNbrJoursDluo = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string nbr_jours_dlv = 9;
 * @return {string}
 */
proto.gestion.Gestion.prototype.getNbrJoursDlv = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setNbrJoursDlv = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional bool gestion_de_lot = 10;
 * @return {boolean}
 */
proto.gestion.Gestion.prototype.getGestionDeLot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setGestionDeLot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool blocage_entree = 11;
 * @return {boolean}
 */
proto.gestion.Gestion.prototype.getBlocageEntree = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setBlocageEntree = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool blocage_sortie = 12;
 * @return {boolean}
 */
proto.gestion.Gestion.prototype.getBlocageSortie = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setBlocageSortie = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string alerte_stock = 13;
 * @return {string}
 */
proto.gestion.Gestion.prototype.getAlerteStock = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setAlerteStock = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string type_alerte = 14;
 * @return {string}
 */
proto.gestion.Gestion.prototype.getTypeAlerte = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.gestion.Gestion} returns this
 */
proto.gestion.Gestion.prototype.setTypeAlerte = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


goog.object.extend(exports, proto.gestion);
